require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.6
  Exclude:
   - 'dummy/db/seeds.rb'
   - 'dummy/db/migrate/**'
   - 'dummy/db/schema.rb'
   - 'lib/generators/templates/**/*'
Documentation:
  Enabled: false
Metrics/LineLength:
  Max: 125
Metrics/ModuleLength:
  Max: 150
Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context']
Layout/CaseIndentation:
  Enabled: false
Style/StructInheritance:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/MixinGrouping:
  Exclude:
    - 'spec/**/*.rb'
Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*.rb'
Gemspec/RequiredRubyVersion:
  Enabled: false
RSpec/ContextWording:
  Enabled: false
RSpec/NestedGroups:
  Enabled: false
RSpec/LetSetup:
  Enabled: false
RSpec/NamedSubject:
  Enabled: false
RSpec/FilePath:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false