AllCops:
  TargetRubyVersion: 2.3
  Exclude:
   - 'spec/dummy/db/seeds.rb'
   - 'spec/dummy/db/migrate/**'
   - 'spec/dummy/db/schema.rb'
   - 'lib/generators/templates/**/*'
Documentation:
  Enabled: false
Metrics/LineLength:
  Max: 125
Style/CaseIndentation:
  Enabled: false
Style/StructInheritance:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Rails/HasAndBelongsToMany:
  Enabled: false
